### ISSUE TITLE
Custom Wallpapers

### ISSUE THREAD

**Issue by claythegamer** [adrianaisemberg/tapet_feedback#3]
Love the app, update looks amazing!
Sorry if this has been answered before or if I'm blind and just can't find the setting.

In a recent update I seem to have lost the ability to shuffle wallpaper images from a directory on the phone.

I have a collection of images I'd like to have tapet shuffle through along with the random generated images. 

Is this still a feature?

**Comment by adrianaisemberg** [comment]
Not yet but it's coming. Stay tuned!
I'm working on rewriting the entire app from scratch. So far I released the most used features and the rest are still in the backlog.

Thanks for your feedback!
