### ISSUE TITLE
Material You colors: Niagara Launcher Anycons and Samsung (also Muzie)

### ISSUE THREAD

**Issue by NelsonMinar** [adrianaisemberg/tapet_feedback#5]
Still love Tapet! Is there some Android API it should be using to notify the system of new colors? Read below for lots of detail.

I use Tapet to change my background once an hour, then the Niagara Launcher picks up the new background colors (via Material You) and colors its icons accordingly. Works great on my Pixel phone and looks terrific, updates automatically. But the icon color settings does not work on Samsung's version of Android.

On Samsung, Niagara always colors its icons blue no matter what the wallpaper is. According to [Niagara's help pages](https://help.niagaralauncher.app/article/133-color-system) this is because
> On Samsung devices, for example, the Material You palette consists by default only of shades of blue, no matter what wallpaper you have applied.

It is possible to change the blue to another static color with the [Samsung Theme Park app](https://www.androidpolice.com/theme-park-color-palette/), but Samsung has done something weird to Material You's palettes so they don't automatically update.

What's vexing is the icon colors do change with the [Muzei wallpaper app](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei&hl=en_US&gl=US). Even on the same Samsung device.

I asked on the Niagara Discord about this and got a comment from a user there who said he was relaying info from the Niagara developer:

> the colour from live wallpapers isn't automatically extracted by launchers, the wallpaper app needs to code it to broadcast an appropriate colour from the image or animated bg

Does that ring a bell? Is there some API Tapet could be calling to help the rest of the system pick up the new colors? It's odd that Niagara+Tapet works on Pixel but not Samsung whereas Muzie works on both. I'm out of my depth here but the Niagara developer is nice, maybe if you reach out to them they'd have some advice.

**Comment by tapet-app** [comment]
Tapet is not a Live-Wallpaper.
The app generates bitmaps and applies them as static wallpapers. As Material-You used to work well on your other devices, I'm afraid this is probably not supported on your current one.

You can test this by applying some random photo from the internet and checking if the color changes.

**Comment by NelsonMinar** [comment]
Thanks for the response and clarifying about Tapet vs Live-Wallpaper. FWIW a Live Wallpaper app (Doodles) displays this text when you run it on a Samsung device:

> Samsung's unfavorable implementation of dynamic colors in One UI 4.1 fully ignores colors provided by live wallpaper apps like Doodle, To apply the colors to your system, set the current design as a static background below to let the system fetch the colors, then re-apply it as live wallpaper.

I tried those instructions and couldn't make it work either. Everyone consistently says the problem is Samsung's. I couldn't even get Muzie's backgrounds to work with Niagara today; not sure what happened yesterday but either I was wrong or it is flaky.

Anyway, it all works great on my Google Pixel device. Tapet is awesome with Material You and dynamic icons. Gonna close this since I don't think there's anything Tapet can do about it.
